dname: amazon
project: debug
model: super_dga
bs: 64
lr: 1e-3
weight_decay: 5e-4
patience: 25
p: 0.3
n_head: 1
n_hidden: 128
BCD: False
grouping: 'hard'
bin_encoding: True
n_bins: 4
stat: 'unclear'
stat_edge: 0
max_epochs: 10000
fanouts: [-1]
seed: 321
usegpu: True
gpuid: 0
debug: False
col_index: None
unclear_ratio: 0
unclear_mid: 0
#dname: yelpchi
#project: fraud_gnn2
#model: super_dga
#bs: 256
#lr: 1e-3
#patience: 25
#p: 0.3
#n_hidden: 32
#BCD: False
#grouping: 'hard'
#bin_encoding: True
#n_bins: 32
#stat: wo
#stat_edge: 0
#max_epochs: 10000
#fanouts: [-1]
#seed: 321
#usegpu: True
#gpuid: 0
#debug: True

