dname: elliptic_of_amnet
project: dga_reproduction
model: dga

# 模型超参数
bin_encoding: True
n_head: 2
n_hidden: 128
p: 0.3
k: 4
z: 0.1
seed: 321

# 训练超参数
bs: 64
lr: 1e-3
weight_decay: 5e-4
max_epochs: 10000
patience: 25
usegpu: True
gpuid: 0
nowandb: False
